/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyfinal_grupo1.JFrame_Forms;

import proyfinal_grupo1.main;

/**
 *
 * @author josue
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnCasosPorEstado = new javax.swing.JButton();
        btnInventarioCritico = new javax.swing.JButton();
        btnFacturacionPorMes = new javax.swing.JButton();
        btnClienteConMasCasos = new javax.swing.JButton();
        btnCasosPorTecnico = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reportes");
        setResizable(false);

        pnlMenu.setBackground(new java.awt.Color(0, 102, 102));

        btnCasosPorEstado.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        btnCasosPorEstado.setText("Casos por Estado");
        btnCasosPorEstado.setAlignmentY(0.0F);
        btnCasosPorEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCasosPorEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasosPorEstadoActionPerformed(evt);
            }
        });

        btnInventarioCritico.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        btnInventarioCritico.setText("Inventario Critico (Menos de 3 Productos)");
        btnInventarioCritico.setAlignmentY(0.0F);
        btnInventarioCritico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInventarioCritico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioCriticoActionPerformed(evt);
            }
        });

        btnFacturacionPorMes.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        btnFacturacionPorMes.setText("Facturacion por Mes");
        btnFacturacionPorMes.setAlignmentY(0.0F);
        btnFacturacionPorMes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFacturacionPorMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionPorMesActionPerformed(evt);
            }
        });

        btnClienteConMasCasos.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        btnClienteConMasCasos.setText("Cliente con mas Casos");
        btnClienteConMasCasos.setAlignmentY(0.0F);
        btnClienteConMasCasos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClienteConMasCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteConMasCasosActionPerformed(evt);
            }
        });

        btnCasosPorTecnico.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        btnCasosPorTecnico.setText("Casos por Tecnico");
        btnCasosPorTecnico.setAlignmentY(0.0F);
        btnCasosPorTecnico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCasosPorTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasosPorTecnicoActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Reportes");

        btnMenu.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCasosPorTecnico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClienteConMasCasos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFacturacionPorMes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInventarioCritico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCasosPorEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addComponent(btnMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo)
                        .addGap(137, 137, 137))))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(btnMenu))
                .addGap(18, 18, 18)
                .addComponent(btnCasosPorEstado)
                .addGap(18, 18, 18)
                .addComponent(btnInventarioCritico)
                .addGap(18, 18, 18)
                .addComponent(btnFacturacionPorMes)
                .addGap(18, 18, 18)
                .addComponent(btnClienteConMasCasos)
                .addGap(18, 18, 18)
                .addComponent(btnCasosPorTecnico)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCasosPorEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasosPorEstadoActionPerformed
        CasosPorEstado casosPorEstado = new CasosPorEstado();
        this.dispose();
        casosPorEstado.setVisible(true);
    }//GEN-LAST:event_btnCasosPorEstadoActionPerformed

    private void btnInventarioCriticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioCriticoActionPerformed
        
    }//GEN-LAST:event_btnInventarioCriticoActionPerformed

    private void btnFacturacionPorMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionPorMesActionPerformed
        
    }//GEN-LAST:event_btnFacturacionPorMesActionPerformed

    private void btnClienteConMasCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteConMasCasosActionPerformed
        
    }//GEN-LAST:event_btnClienteConMasCasosActionPerformed

    private void btnCasosPorTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasosPorTecnicoActionPerformed
        
    }//GEN-LAST:event_btnCasosPorTecnicoActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        if (main.Administrador){
            MenuAdmin menuA = new MenuAdmin();
            this.dispose();
            menuA.setVisible(true);
        }else{
            MenuEmpleado menuE = new MenuEmpleado();
            this.dispose();
            menuE.setVisible(true);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCasosPorEstado;
    private javax.swing.JButton btnCasosPorTecnico;
    private javax.swing.JButton btnClienteConMasCasos;
    private javax.swing.JButton btnFacturacionPorMes;
    private javax.swing.JButton btnInventarioCritico;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
